### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by TildaDares** [kwambugu/Jumpstart-Lab-s-Blogger-Tutorial#1]
Hi, I'm currently working on the blogger project but I can't get my flash messages to show. I've tried solutions from the internet but nothing seems to be working. I'd like to know if you had any troubles too and how you solved it. My github repo link: https://github.com/TildaDares/blogger. Thank you.

**Comment by Clinton-dev** [comment]
Can I check it tomorrow it's 2am here

**Comment by TildaDares** [comment]
Sure. Thanks for replying.

**Comment by Clinton-dev** [comment]
I cant seem to find where the problem is. The code is exactly the same but I have noticed you are using different version of ruby (am using 2.6.5 I dont have a ruby version manager so i cant replicate the exact scenario).maybe  I could take another stab at it tomorrow if that fails you can always ask on ToP's discord or stack overflow if you dare 😄 .

**Comment by Clinton-dev** [comment]
what if you wrote ``` flash[:notice] = "Article #{@article.name}' was updated" ``` and then in the layout: ``` <%= flash[:notice]%>```

**Comment by TildaDares** [comment]
Thanks I'll try that.

**Comment by Clinton-dev** [comment]
we should exchange contacts that's if you dont mind

**Comment by TildaDares** [comment]
Social media accounts?

**Comment by Clinton-dev** [comment]
Yeah am on Twitter : @wambugu clinton

**Comment by TildaDares** [comment]
Just followed you

**Comment by Clinton-dev** [comment]
were you able to fix the issue?

**Comment by TildaDares** [comment]
Yes I did. Thank you
